pyerror/__init__.py,sha256=MBY48x3s5-m8FnmbTvOGcGkJ1R81a3q0-RTKPKqfxqM,6908
pyerror/info.py,sha256=waSfurOqxM9kqNUHpMnnlq4CugYcpVlryckwPP7lm9I,21
pyerror/templates.py,sha256=xofmtHZaZ9_Hn4pEV8CeMbeA5WGl0sxoPsPvl9LY1sg,1564
PyErrManager-2.0.dist-info/LICENSE,sha256=TQJbBL8jyGeNbscHvbtasS147Dl98EG9GEsvT5KT8Lo,1076
PyErrManager-2.0.dist-info/METADATA,sha256=I6n7l-DX2jULTCbxBIRjAJwmR_gi8HNtSfuQtM09BQ0,834
PyErrManager-2.0.dist-info/WHEEL,sha256=v8slff5hmCpvciQ3G55d2d1CnOBupjDFJHDE2dUb1Ao,97
PyErrManager-2.0.dist-info/top_level.txt,sha256=U7fIP1nhM-2rb-DL3CUUKyfGpFLv1N3c_Df0s_wXpmU,8
PyErrManager-2.0.dist-info/RECORD,,
